
name: Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the project and generate JAR
        run: mvn clean package -DskipTests # Générez le fichier JAR
        working-directory: ./aipasswordcheck # Si votre projet est dans un sous-répertoire, ajustez le chemin

      - name: Run Performance Testing
        run: java -jar ./aipasswordcheck/target/my-app.jar --performancetest # Remplacez avec le nom correct du fichier JAR
        working-directory: ./aipasswordcheck # Ajustez si nécessaire
